site_name: it-hub-operations
site_description: "Main documentation for it-hub-operations project"
repo_url: https://github.com/xgeeks-geekathon/it-hub-operations.git
edit_uri: edit/master/docs

# plugins:
#   - techdocs-core

# For sidebar navigation
nav:
  - Getting Started: "index.md"
